// import type { Metadata } from "next";
// import { Geist } from "next/font/google";
// // import "./globals.css"; 
// import { ClerkProvider } from "@clerk/nextjs";
// import ConvexClerkProvider from "@/components/providers/ConvexClerkProvider";

// const geist = Geist({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ConvexClerkProvider>
//     <html lang="en">
//       <body className="" >
//         {children}
//       </body>
//     </html>
//     </ConvexClerkProvider>
//   );
// }


import type { Metadata } from "next";
//import localFont from "next/font/local";
import "@stream-io/video-react-sdk/dist/css/styles.css";
import "./globals.css";
import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import ConvexClerkProvider from "@/components/providers/ConvexClerkProvider";
import Navbar from "@/components/Navbar";
// import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
// import { useRouter } from "next/router";
// import { usePathname } from "next/navigation";
// import { useQuery } from "convex/react";
// import { api } from "../../convex/_generated/api";
// import { useEffect } from "react";
import RoleGate from "@/components/guards/RoleGate";
import 'tw-animate-css';
import FAQChat from "@/components/FAQChat";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ConvexClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body 
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SignedIn>
              <div className="min-h-screen">
                <Navbar />
                {/* <main className="px-4 sm:px-6 lg:px-8">{children}</main> */}
                <main className="px-4 sm:px-6 lg:px-8">
                    <RoleGate>{children}</RoleGate> {/* 👈 add this wrapper */}
                </main>
                <FAQChat/>
                
              </div>
            </SignedIn>

            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
          </ThemeProvider>
          <Toaster />
        </body>
      </html>
    </ConvexClerkProvider>
  );
}